server.port=8081
keycloak.auth-server-url=http://keycloak:8080
keycloak.realm=spring-keycloak-demo
keycloak.resource=spring-app
keycloak.public-client=true
keycloak.principal-attribute=preferred_username
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2.jwt=DEBUG
keycloak.use-resource-role-mappings=false
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/spring-keycloak-demo
